{  "Info" "ISGN_NUM_OF_BLACKBOXED_DESIGN_UNITS_AND_ENTITIES" "C:\\Users\\M-H-KARAMI\\Desktop\\16-bit-cpu\\files\\cpu.gdf 1 1 " "Black-boxed 1 design units and 1 entities in source file C:\\Users\\M-H-KARAMI\\Desktop\\16-bit-cpu\\files\\cpu.gdf" { { "Info" "ISGN_BLACKBOXED_ENTITY_NAME" "1 cpu " "Black-boxed entity 1: cpu" {  } { { "C:\\Users\\M-H-KARAMI\\Desktop\\16-bit-cpu\\files\\cpu.gdf" "cpu" "" { Schematic "C:\\Users\\M-H-KARAMI\\Desktop\\16-bit-cpu\\files\\cpu.gdf" { { } } } }  } 0}  } {  } 0 }
{  "Error" "ESGN_ENTITY_VTOP" "cpu " "Top-level entity cpu is not from a Verilog or VHDL source." {  } {  } 0 }
{  "Info" "IQCU_REPORT_WRITTEN_TO" "cpu.syn.rpt " "Writing report to file cpu.syn.rpt" {  } {  } 0 }
{  "Info" "IQEXE_WHITESPACE" "" "" {  } {  } 0 }
{  "Error" "EQEXE_SEPARATOR" "" "*********************************************************" {  } {  } 0 }
{  "Error" "EQEXE_ERROR_COUNT" "Software 1  0 s " "MAX+PLUS II Advanced Synthesis Software was unsuccessful. 1 error, 0 warnings" {  } {  } 0 }
{  "Error" "EQEXE_END_BANNER_TIME" "Sat Feb 02 17:29:39 2019 " "Processing ended: Sat Feb 02 17:29:39 2019" {  } {  } 0 }
{  "Error" "EQEXE_SEPARATOR" "" "*********************************************************" {  } {  } 0 }
